require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  
  config.env.enable
  config.ssh.username = 'ubuntu'  
  config.ssh.private_key_path = ENV['KEY_PATH']

  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name        = ENV['OS_DOMAIN_NAME']
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.tenant_name        = ENV['OS_TENANT_NAME']  
    os.project_name       = ENV['OS_PROJECT_NAME']
    os.keypair_name       = ENV['OS_KEY_PAIR_NAME']
    os.region             = ENV['OS_REGION_NAME']
    os.image              = ENV['OS_IMAGE']
  end

  config.vm.define ENV['BOX_NAME'] do |s|
    s.vm.provision "shell", path: "./scripts/nodejs-install.sh"
    s.vm.provision "shell", path: "./scripts/oracle-jdk-install.sh"
    s.vm.provision "docker" do | docker |
      docker.pull_images "mongo"
      docker.pull_images "cassandra"
    end
    s.vm.provision "docker_compose" 
    s.vm.provider :openstack do |os, override|
      os.server_name = ENV['OS_SERVER_NAME']
      os.flavor = ENV['OS_FLAVOR']
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end
  end
end
